#!/usr/bin/env -S python3 -u

import hashlib
import argparse, socket, time, json, select, struct, sys, math

class Receiver:
    def __init__(self):
        self.delivered = set()
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)

        self.remote_host = None
        self.remote_port = None

        self.cumulative_ack = -1 #highest sequence number that is the garunteed to have been recieved by reciever
        self.sack_blocks = [] #SACK block lower and upper bound pairs

        self.buffer_dictionary = dict() #dictionary of sequence number to data for out of order packets
        self.seq_buffer_pointer = -1 #pointer to next seq num that we wait for

    #obv this only works if we already recieved message and actually update the remote host/port fields
    def send(self, message):
        self.log("Sent message %s" % json.dumps(message))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.remote_host, self.remote_port))

    #Updates to get the remote host/port from the first message that is recieved
    #Also checks if the message is from same remote host/port and returns the message if it is
    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Grab the remote host/port if we don't already have it
        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        # Make sure we're talking to the same remote host
        if addr != (self.remote_host, self.remote_port):
            self.log("Error:  Received response from unexpected remote; ignoring")
            return None
        else:
            # self.log("Received message %s" % json.loads(data.decode("utf-8"))["data"][:25])
            try:
                msg = json.loads(data.decode("utf-8"))
                if "data" not in msg:
                    self.log("Corrupted packet dropped")
                    return None

                self.log("Received message %s" % msg["data"][:25])
                return msg
            except:
                self.log("Corrupted packet dropped")
                return None

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()
    
    
    def determine_adjacent(self,sack_block,seq_num):
        lower_bound = sack_block[0]
        upper_bound = sack_block[1]
        if lower_bound - 1 == seq_num:
            return "lower"
        elif upper_bound + 1 == seq_num:
            return "upper"
        else:
            return "none"

    def find_sack_block_avg(self,sack_block):
        lower_bound = sack_block[0]
        upper_bound = sack_block[1]
        return (lower_bound + upper_bound) / 2
    
    def rebuild_sack_blocks(self):
        seqs = sorted(self.buffer_dictionary.keys())
        blocks = []

        start = None
        prev = None

        for s in seqs:
            if s <= self.cumulative_ack:
                continue

            if start is None:
                start = s
                prev = s
            elif s == prev + 1:
                prev = s
            else:
                blocks.append([start, prev])
                start = s
                prev = s

        if start is not None:
            blocks.append([start, prev])

        return blocks

    def is_data_corrupted(self, msg):
        expected = hashlib.md5(msg["data"].encode()).hexdigest()
        return expected != msg["checksum"]
    
    def run(self):
        while True:
            socks = select.select([self.socket], [], [])[0] #This weits until we get a message packet on the scoket
            for conn in socks:
                msg = self.recv(conn)
                if not msg:
                    continue

                if msg:
                    if self.is_data_corrupted(msg):
                        self.log("Corrupted packet dropped")
                        continue #skip processing completely
                    
                    if "type" not in msg or "seq" not in msg or "data" not in msg:
                        self.log("Malformed packet dropped")
                        continue

                    # Print out the data to stdout in order
                    seq_num = msg["seq"]
                    data = msg["data"]

                    if seq_num not in self.buffer_dictionary:
                        self.buffer_dictionary[seq_num] = data  
                          
                    while (self.cumulative_ack + 1) in self.buffer_dictionary:
                        self.cumulative_ack += 1
                        print(self.buffer_dictionary[self.cumulative_ack], end='', flush=True)
                        del self.buffer_dictionary[self.cumulative_ack]

                    self.sack_blocks = self.rebuild_sack_blocks()

                    # Always send back an ack
                    #self.send({ "type": "ack", "seq": msg["seq"] })
                    # self.send({ "type": "ack", "cum_ack": self.cumulative_ack, "sack_blocks":self.sack_blocks })
                    self.send({
                        "type": "ack",
                        "ack": self.cumulative_ack,
                        "sack": self.sack_blocks
                    })


        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    sender = Receiver()
    sender.run()
