#!/usr/bin/env -S python3 -u

import numbers
import argparse, socket, time, json, select, struct, sys, math

DATA_SIZE = 1375

class Sender:
    def __init__(self, host, port):
        self.host = host #host and port are the remote host/port we want to send to
        self.port = int(port)
        self.log("Sender starting up using port %s" % self.port)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))

        self.window_size = 4

        self.left_window_bound = 0
        self.right_window_bound = self.window_size - 1
        self.acked_in_window_msgs = set() #set of sequence numbers that have been acked by the receiver, but are still in the current window
        #self.unacked_msgs = set() #set of sequence numbers that have been sent but not yet acked by the receiver
        self.unacked_msgs = dict() #dictionary of sequence numbers with strikes that have been sent but not yet acked by the receiver

        self.resend_queue = [] #queue of sequence numbers that need to be resent
        self.timeout_duration = 1.5
        self.oldest_packet_timestamp = None

        self.missing_ack_sequence_list = []
        self.latest_sack_blocks = None
        self.cumulative_ack = -1

        self.shutdown_phase = False
        self.recv_cumulative_ack = -2
        self.latest_sequence_sent = -1

        self.remote_host = None
        self.remote_port = None #remote host/port should be the same as host/port but we will update it when we get the first message back from the remote host to make sure we're talking to the same remote host/port

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, message):
        new_message = message["data"][:25]
        self.log("Sending message '%s'" % json.dumps(new_message))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.host, self.port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Grab the remote host/port if we don't already have it
        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        # Make sure we're talking to the same remote host
        if addr != (self.remote_host, self.remote_port):
            self.log("Error:  Received response from unexpected remote; ignoring")
            return None
        else:
            self.log("Received message %s" % data)
            return json.loads(data.decode("utf-8"))

    def get_longest_consecutive_from_min(self,numbers):
        if not numbers:
            return []
        sorted_uniques = sorted(list(set(numbers)))
    
        longest_seq = []
        current_val = sorted_uniques[0]
    
        for num in sorted_uniques:
            if num == current_val:
                longest_seq.append(num)
                current_val += 1
            else:
                break
            
        return longest_seq
    
    def find_missing_seq(self,sack_blocks,cumulative_ack):
        missing_acks = []
        ack_pointer = cumulative_ack
        for sack_block in sack_blocks:
            lower_bound = sack_block[0]
            upper_bound = sack_block[1]
            missing_acks.extend(list(range(ack_pointer + 1,lower_bound)))
            ack_pointer = upper_bound
        return missing_acks

    #assumes that ack already has entry in dictionary
    #given an ack_num, increment strike count in unacked_msgs dictionary and return true if we need to resend the message(reset count if we do)
    def process_ack_strike(self, ack_num):
        if ack_num not in self.unacked_msgs:
            return False
        self.unacked_msgs[ack_num][0] += 1
        if self.unacked_msgs[ack_num][0] >= 3:
            self.unacked_msgs[ack_num][0] = 0 #reset the strike count and resend it
            self.resend_queue.append(ack_num) #add to resend queue
            self.log("Ack %d strike count: %d" % (ack_num, self.unacked_msgs[ack_num][0]))
            return True
        self.log("Ack %d strike count: %d" % (ack_num, self.unacked_msgs[ack_num][0]))
        return False #don't resend it

    def merge_sack_blocks(self,sack_block1,sack_block2):
            if sack_block1[0] <= sack_block2[0] and sack_block1[1] >= sack_block2[0] - 1: #if sack block 1 is to the left of sack block 2 and they are adjacent or overlapping, merge them
                return [min(sack_block1[0],sack_block2[0]),max(sack_block1[1],sack_block2[1])]
            elif sack_block2[0] <= sack_block1[0] and sack_block2[1] >= sack_block1[0] - 1: #if sack block 2 is to the left of sack block 1 and they are adjacent or overlapping, merge them
                return [min(sack_block1[0],sack_block2[0]),max(sack_block1[1],sack_block2[1])]
            else:
                return None

    def merge_sack_block_lists(self,sack_blocks1,sack_blocks2):
            if sack_blocks1 is None: sack_blocks1 = []
            if sack_blocks2 is None: sack_blocks2 = []
            merged_sack_blocks = []
            i = 0
            j = 0
            while i < len(sack_blocks1) and j < len(sack_blocks2):
                merged_block = self.merge_sack_blocks(sack_blocks1[i],sack_blocks2[j])
                if merged_block:
                    merged_sack_blocks.append(merged_block)
                    i += 1
                    j += 1
                elif sack_blocks1[i][0] < sack_blocks2[j][0]:
                    merged_sack_blocks.append(sack_blocks1[i])
                    i += 1
                else:
                    merged_sack_blocks.append(sack_blocks2[j])
                    j += 1
            while i < len(sack_blocks1):
                merged_sack_blocks.append(sack_blocks1[i])
                i += 1
            while j < len(sack_blocks2):
                merged_sack_blocks.append(sack_blocks2[j])
                j += 1
            return merged_sack_blocks

    def absorb_sacks(self, cumulative_ack, sack_blocks):
        """
        Consolidates SACK blocks into the cumulative_ack if they touch or overlap.
        Returns the new cumulative_ack and the remaining (unabsorbed) sack_blocks.
        """
        if not sack_blocks:
            return cumulative_ack, []

        # Ensure blocks are sorted by start sequence
        sack_blocks.sort()
        
        # Merge overlapping or adjacent SACK blocks first
        merged = []
        curr_start, curr_end = sack_blocks[0]
        for next_start, next_end in sack_blocks[1:]:
            if next_start <= curr_end + 1:
                curr_end = max(curr_end, next_end)
            else:
                merged.append([curr_start, curr_end])
                curr_start, curr_end = next_start, next_end
        merged.append([curr_start, curr_end])

        # Absorb merged blocks into the mainland
        final_sacks = []
        new_cum_ack = cumulative_ack
        
        for start, end in merged:
            # If block touches or is behind the mainland, it's absorbed
            if start <= new_cum_ack + 1:
                new_cum_ack = max(new_cum_ack, end)
            else:
                # It's still an island
                final_sacks.append([start, end])

        return new_cum_ack, final_sacks

    def determine_seq_in_sack_block(self,sack_block,seq_num):
        if sack_block[0] <= seq_num <= sack_block[1]:
            return True
        return False
    
    #given a sack block list, determine if seq num is in any of the sack blocks return true if it is
    def if_seq_in_sack_blocks(self,sack_blocks,seq_num):
        for sack_block in sack_blocks:
            if self.determine_seq_in_sack_block(sack_block,seq_num):
                return True
        return False
    
    def is_seq_hole(self,sack_blocks,seq_num):
        for sack_block in sack_blocks:
            if sack_block[0] > seq_num:
                return True
        return False
    
    def is_sack_block_list_changed(self,sack_blocks1,sack_blocks2):
        if sack_blocks1 is None: sack_blocks1 = []
        if sack_blocks2 is None: sack_blocks2 = []
        if len(sack_blocks1) != len(sack_blocks2):
            return True
        for i in range(len(sack_blocks1)):
            if sack_blocks1[i][0] != sack_blocks2[i][0] or sack_blocks1[i][1] != sack_blocks2[i][1]:
                return True
        return False

    def process_ack(self, data):
            if not data or data["type"] != "ack":
                return
            
            new_cum_ack = data["cum_ack"]
            old_cumulative_ack = self.cumulative_ack
            self.cumulative_ack = max(self.cumulative_ack, new_cum_ack) #update to find highest cumulative ack seen so far
            is_cumulative_ack_changed = False
            if self.cumulative_ack != old_cumulative_ack:
                is_cumulative_ack_changed = True
            sack_blocks = data["sack_blocks"]
            #self.recv_cumulative_ack = new_cum_ack
            
            
            #self.missing_ack_sequence_list = self.find_missing_seq(sack_blocks,new_cum_ack) #FIX THIS LATER
            new_sack_blocks_temporary = self.merge_sack_block_lists(self.latest_sack_blocks,sack_blocks)
            is_sack_block_list_changed = self.is_sack_block_list_changed(self.latest_sack_blocks,new_sack_blocks_temporary)
            self.latest_sack_blocks = new_sack_blocks_temporary
            self.cumulative_ack, self.latest_sack_blocks = self.absorb_sacks(self.cumulative_ack,self.latest_sack_blocks)
                    
            #Handles updating unacked_msgs, acked_in_window_msgs, and adding strikes to unacked messages that are holes
            for seq in list(self.unacked_msgs.keys()):
                if seq <= self.cumulative_ack: #if seq num to left of cumulative ack, then we can safely delete it from unacked msgs and acked in window
                    del self.unacked_msgs[seq]
                    if seq in self.acked_in_window_msgs:
                        self.acked_in_window_msgs.remove(seq)
                else: #if seq num to right of cumulative ack,
                    if self.if_seq_in_sack_blocks(self.latest_sack_blocks,seq):
                        del self.unacked_msgs[seq]
                        self.acked_in_window_msgs.add(seq)
                    else:
                        if self.is_seq_hole(self.latest_sack_blocks,seq) and (is_cumulative_ack_changed or is_sack_block_list_changed):
                            self.process_ack_strike(seq)

            #HANDLES WINDOW SLIDING
            if self.cumulative_ack + 1 > self.left_window_bound:
                self.left_window_bound = self.cumulative_ack + 1
                while self.left_window_bound in self.acked_in_window_msgs:
                    self.acked_in_window_msgs.remove(self.left_window_bound)
                    self.left_window_bound += 1
                #directly fix the right window bound entirely on left window bound instead of seperate calc
                self.right_window_bound = self.left_window_bound + self.window_size - 1

            #This handles RTO timing
            if not self.unacked_msgs:
                self.oldest_packet_timestamp = None
            elif is_cumulative_ack_changed:
                # The 'Mainland' moved, so the 'oldest' packet changed. 
                # Restart the timer for the new oldest packet.
                self.oldest_packet_timestamp = time.time()


    '''def send_msg(self, current_seq, data=None):
        if data is not None:
            pass
        else:
            data = sys.stdin.read(DATA_SIZE)
            self.unacked_msgs[current_seq] = [0, data, time.time()]
            self.latest_sequence_sent = current_seq
        if len(data) == 0:
            #no more data to read
            self.shutdown_phase = True
            self.log("Activating shutdown phase")
            return
        msg = { "type": "msg", "data": data, "seq": current_seq }
        self.send(msg)
        

        if self.oldest_packet_timestamp is None:
            self.oldest_packet_timestamp = time.time()'''
    def send_msg(self, current_seq, data=None):
            # Case A: Retransmission (data is already provided)
            if data is not None:
                msg = { "type": "msg", "data": data, "seq": current_seq }
                self.send(msg)
            
            # Case B: First-time send (must read from stdin)
            else:
                new_data = sys.stdin.read(DATA_SIZE)
                if len(new_data) == 0:
                    self.shutdown_phase = True
                    # self.log("End of file reached.") # Optional log
                    return # STOP HERE. Do not update latest_sequence_sent.
                
                # Only save and update goalpost if we actually got data!
                self.unacked_msgs[current_seq] = [0, new_data, time.time()]
                self.latest_sequence_sent = current_seq
                
                msg = { "type": "msg", "data": new_data, "seq": current_seq }
                self.send(msg)

            # Start timer if this is the first packet in flight
            if self.oldest_packet_timestamp is None:
                self.oldest_packet_timestamp = time.time()
    

    
    def check_timeout(self):
        if self.oldest_packet_timestamp is None: return
        
        if time.time() - self.oldest_packet_timestamp >= self.timeout_duration:
            target = self.cumulative_ack + 1
            
            # Only resend if the target is a real packet we actually sent!
            if target <= self.latest_sequence_sent and target in self.unacked_msgs:
                self.log(f"TIMEOUT: Resending actual missing packet {target}")
                self.resend_queue.append(target)
                self.unacked_msgs[target][0] = 0 
                
            self.oldest_packet_timestamp = time.time()

    
    def run(self):
        current_seq = 0
        while True:# if self.shutdown_phase and not self.unacked_msgs:
            if self.shutdown_phase and self.cumulative_ack >= self.latest_sequence_sent: # and self.recv_cumulative_ack == self.latest_sequence_sent: #if we are in shutdown phase and have no more unacked msgs then we can exit
                sys.exit(0)
            self.check_timeout()
            sockets = [self.socket, sys.stdin] if current_seq <= self.right_window_bound else [self.socket] #only read from sdtin IF window is not full
            if self.shutdown_phase:
                sockets = [self.socket] #if we're in shutdown phase don't read from stdin at all
            socks = select.select(sockets, [], [], 0.1)[0]

            for sequence in self.resend_queue: #resend all messages in the resend queue before reading new input
                self.send_msg(sequence,self.unacked_msgs[sequence][1])
            self.resend_queue = []
            for conn in socks:
                if conn == self.socket:
                    data = self.recv(conn)
                    self.log("Processing ack with sack blocks %s and cumulative ack %s" % (data["sack_blocks"],data["cum_ack"]))
                    self.process_ack(data)
                
                elif conn == sys.stdin: #ready from stdin the user input if it exists

                    while current_seq <= self.right_window_bound and self.shutdown_phase == False:#while loop reads from stdin until we fill up the window.
                        self.send_msg(current_seq)
                        current_seq += 1

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run()
