#!/usr/bin/env -S python3 -u

import numbers
import argparse, socket, time, json, select, struct, sys, math

DATA_SIZE = 1375

class Sender:
    def __init__(self, host, port):
        self.host = host #host and port are the remote host/port we want to send to
        self.port = int(port)
        self.log("Sender starting up using port %s" % self.port)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))

        self.window_size = 3

        self.left_window_bound = 0
        self.right_window_bound = self.window_size - 1
        self.acked_in_window_msgs = set() #set of sequence numbers that have been acked by the receiver
        self.unacked_msgs = set() #set of sequence numbers that have been sent but not yet acked by the receiver


        self.remote_host = None
        self.remote_port = None #remote host/port should be the same as host/port but we will update it when we get the first message back from the remote host to make sure we're talking to the same remote host/port

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, message):
        self.log("Sending message '%s'" % json.dumps(message))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.host, self.port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Grab the remote host/port if we don't already have it
        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        # Make sure we're talking to the same remote host
        if addr != (self.remote_host, self.remote_port):
            self.log("Error:  Received response from unexpected remote; ignoring")
            return None
        else:
            self.log("Received message %s" % data)
            return json.loads(data.decode("utf-8"))

    #determines if we can move the window forward by checking if the oldest unacked message has been acked. if it is then we say true
    def can_window_move(self):
        return self.left_window_bound not in self.unacked_msgs
    
    
    def get_longest_consecutive_from_min(self,numbers):
        if not numbers:
            return []
        sorted_uniques = sorted(list(set(numbers)))
    
        longest_seq = []
        current_val = sorted_uniques[0]
    
        for num in sorted_uniques:
            if num == current_val:
                longest_seq.append(num)
                current_val += 1
            else:
                break
            
        return longest_seq

    def process_ack(self, data):
        if data and data["type"] == "ack":
            ack_sequence = data["seq"]
            if ack_sequence in self.unacked_msgs: #already guards against duplicates
                #add a check on this line for duplicate ACK concerns
                self.acked_in_window_msgs.add(ack_sequence)
                self.unacked_msgs.remove(ack_sequence)
                            

            if self.left_window_bound in self.acked_in_window_msgs: #if this passes, window_shift needs to be done
                window_shift_length = len(self.get_longest_consecutive_from_min(self.acked_in_window_msgs)) #this gets us the amount we need to shift by
                for i in range(window_shift_length):
                    self.acked_in_window_msgs.remove(self.left_window_bound + i) #remove the acked messages that are no longer in the window from the set of acked messages in the window
                self.left_window_bound += window_shift_length
                self.right_window_bound += window_shift_length


    def send_msg(self, current_seq):
        data = sys.stdin.read(DATA_SIZE)
        if len(data) == 0:
            self.log("All done!")
            sys.exit(0)
        msg = { "type": "msg", "data": data, "seq": current_seq }
        self.send(msg)
        self.unacked_msgs.add(current_seq)
    
    def run(self):
        current_seq = 0
        while True:
            sockets = [self.socket, sys.stdin] if current_seq <= self.right_window_bound else [self.socket] #only read from sdtin IF window is not full
            socks = select.select(sockets, [], [], 0.1)[0]

            for conn in socks:
                if conn == self.socket:
                    data = self.recv(conn)
                    self.process_ack(data)
                
                elif conn == sys.stdin: #ready from stdin the user input if it exists
                    while current_seq <= self.right_window_bound:#while loop reads from stdin until we fill up the window.
                        self.send_msg(current_seq)
                        current_seq += 1

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run()
