#!/usr/bin/env -S python3 -u

import hashlib
import argparse, socket, time, json, select, struct, sys, math

class Receiver:
    def __init__(self):
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)
        
        self.total_dictionary = dict() #dictionary of sequence numbers collected

        self.remote_host = None
        self.remote_port = None

        self.cumulative_ack = -1 #highest sequence number that is the garunteed to have been recieved by reciever
        self.sack_blocks = [] #SACK block lower and upper bound pairs

        self.buffer_dictionary = dict() #dictionary of sequence number to data for out of order packets
        self.seq_buffer_pointer = -1 #pointer to next seq num that we wait for

    #obv this only works if we already recieved message and actually update the remote host/port fields
    def send(self, message):
        self.log("Sent message %s" % json.dumps(message))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.remote_host, self.remote_port))

    #Updates to get the remote host/port from the first message that is recieved
    #Also checks if the message is from same remote host/port and returns the message if it is
    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Grab the remote host/port if we don't already have it
        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        # Make sure we're talking to the same remote host
        if addr != (self.remote_host, self.remote_port):
            self.log("Error:  Received response from unexpected remote; ignoring")
            return None
        else:
            self.log("Received message %s" % json.loads(data.decode("utf-8"))["data"][:25])
            #self.log("Received message %s" % json.dumps(data))
            return json.loads(data.decode("utf-8"))

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()
    
    
    def determine_adjacent(self,sack_block,seq_num):
        lower_bound = sack_block[0]
        upper_bound = sack_block[1]
        if lower_bound - 1 == seq_num:
            return "lower"
        elif upper_bound + 1 == seq_num:
            return "upper"
        else:
            return "none"

    def find_sack_block_avg(self,sack_block):
        lower_bound = sack_block[0]
        upper_bound = sack_block[1]
        return (lower_bound + upper_bound) / 2
    
    def update_SACK_blocks(self,sack_blocks,seq_num):
        if len(sack_blocks) == 0:
            sack_blocks.append([seq_num,seq_num])
            return sack_blocks

        avg_list = [self.find_sack_block_avg(sack_block) for sack_block in sack_blocks]
        #print(avg_list)
        lower_bound_index = 0
        upper_bound_index = len(sack_blocks) - 1
        while upper_bound_index - lower_bound_index > 1:
            middle_index = (lower_bound_index + upper_bound_index) // 2
            if avg_list[middle_index] < seq_num:
                lower_bound_index = middle_index
            else:
                upper_bound_index = middle_index
        #print(lower_bound_index,upper_bound_index)
        #print(sack_blocks[lower_bound_index],sack_blocks[upper_bound_index])

        lower_block = sack_blocks[lower_bound_index]
        upper_block = sack_blocks[upper_bound_index]

        if self.determine_adjacent(lower_block,seq_num) == "lower":
            sack_blocks[lower_bound_index][0] -= 1
        elif self.determine_adjacent(upper_block,seq_num) == "upper":
            sack_blocks[upper_bound_index][1] += 1
        elif self.determine_adjacent(lower_block,seq_num) == "none" and self.determine_adjacent(upper_block,seq_num) == "none":
            lower_bound_avg = self.find_sack_block_avg(lower_block)
            upper_bound_avg = self.find_sack_block_avg(upper_block)
            if lower_bound_avg > seq_num:
                sack_blocks.insert(lower_bound_index, [seq_num,seq_num])
            elif upper_bound_avg < seq_num:
                sack_blocks.insert(upper_bound_index + 1, [seq_num,seq_num])
            else:
                sack_blocks.insert(lower_bound_index + 1, [seq_num,seq_num])
        elif self.determine_adjacent(lower_block,seq_num) == "upper" and self.determine_adjacent(upper_block,seq_num) == "lower":
            sack_blocks[lower_bound_index][1] = sack_blocks[upper_bound_index][1]
            del sack_blocks[upper_bound_index]
        elif self.determine_adjacent(lower_block,seq_num) == "upper":
            sack_blocks[lower_bound_index][1] += 1
        elif self.determine_adjacent(upper_block,seq_num) == "lower":
            sack_blocks[upper_bound_index][0] -= 1
        return sack_blocks
    
    def is_data_corrupted(self, msg):
        expected = hashlib.md5(msg["data"].encode()).hexdigest()
        return expected != msg["checksum"]
    
    def cum_ack_absorb(self,sack_blocks,cumulative_ack):
        if sack_blocks:
            self.log("SACK blocks before absorption: %s, cumulative_ack: %d" % (sack_blocks,cumulative_ack))
            for sack_block in sack_blocks.copy():
                lower_bound = sack_block[0]
                upper_bound = sack_block[1]
                old_cumulative_ack = cumulative_ack

                if abs(lower_bound - cumulative_ack) <= 1:
                    cumulative_ack = upper_bound
                    sack_blocks.remove(sack_block)
                elif lower_bound <= cumulative_ack: #sack block needs to be absorbed.
                    sack_blocks.remove(sack_block)
                    if upper_bound > cumulative_ack:
                        cumulative_ack = upper_bound
                
                while old_cumulative_ack < cumulative_ack: #go from old cumulative ack to the new cumulative ack to print out all sequence data left of the new cumulative ack.
                    old_cumulative_ack += 1
                    if old_cumulative_ack in self.buffer_dictionary:
                        print(self.buffer_dictionary[old_cumulative_ack],end='',flush=True)
                        del self.buffer_dictionary[old_cumulative_ack]
            
            counter = 0
            while counter < len(sack_blocks) - 1:
                if self.merge_sack_blocks(sack_blocks[counter],sack_blocks[counter + 1]):
                    sack_blocks[counter] = self.merge_sack_blocks(sack_blocks[counter],sack_blocks[counter + 1])
                    del sack_blocks[counter + 1]
                else:
                    counter += 1
            self.log("SACK blocks after absorption: %s, cumulative_ack: %d" % (sack_blocks,cumulative_ack))
            
        return sack_blocks,cumulative_ack
    
    def merge_sack_blocks(self, sack_block1, sack_block2):
        sack_block1_lower_bound = sack_block1[0]
        sack_block1_upper_bound = sack_block1[1]
        sack_block2_lower_bound = sack_block2[0]
        sack_block2_upper_bound = sack_block2[1]

        if sack_block1_upper_bound >= sack_block2_lower_bound or sack_block2_upper_bound >= sack_block1_lower_bound:
            return [min(sack_block1_lower_bound,sack_block2_lower_bound),max(sack_block1_upper_bound,sack_block2_upper_bound)]
        else:            return None

    def run(self):
        while True:
            socks = select.select([self.socket], [], [])[0] #This waits until we get a message packet on the scoket
            for conn in socks:
                msg = self.recv(conn)

                if msg:
                    if self.is_data_corrupted(msg):
                        self.log("Corrupted packet dropped")
                        continue #skip processing completely
                    
                    if "type" not in msg or "seq" not in msg or "data" not in msg:
                        self.log("Malformed packet dropped")
                        continue

                    # Print out the data to stdout in order
                    #print(msg["data"], end='', flush=True)
                    seq_num = msg["seq"]
                    data = msg["data"]

                    self.buffer_dictionary[seq_num] = data

                    self.total_dictionary[seq_num] = data


                    
                    
                    self.sack_blocks = self.update_SACK_blocks(self.sack_blocks,seq_num) #maybe make it regenerate SACK blocks from buffer dictionary every time???
                    self.sack_blocks,self.cumulative_ack = self.cum_ack_absorb(self.sack_blocks,self.cumulative_ack)

                    # Always send back an ack
                    #self.send({ "type": "ack", "seq": msg["seq"] })
                    string_of_total_keys = ','.join(str(key) for key in sorted(self.total_dictionary.keys()))
                    missing_keys = [key for key in range(min(self.total_dictionary.keys()),max(self.total_dictionary.keys()) + 1) if key not in self.total_dictionary]
                    self.log("total dictionary keys: %s" % string_of_total_keys)
                    self.log("missing keys: %s" % missing_keys)
                    self.log("length: %d" % len(self.total_dictionary))
                    self.send({ "type": "ack", "cum_ack": self.cumulative_ack, "sack_blocks":self.sack_blocks })


        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    sender = Receiver()
    sender.run()
